version: "3"

services:

  application:
    build: .
    container_name: application
    environment:
      - MONGO_URL=mongodb://db:27017
      - DB_NAME=test
    ports:
      - "8080:8080"
    volumes:
      - "./:/code"
    depends_on:
      - db
  
  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"